version: '3.4'

services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:${NETBOX_VERSION:-v2.11.12}
    container_name: netbox
    hostname: netbox
    restart: always
    depends_on:
      - postgres
      - redis
      - redis-cache
      - netbox-worker
    env_file: env/netbox.env
    user: '101'
    volumes:
      - ./startup_scripts:/opt/netbox/startup_scripts
      - ./initializers:/opt/netbox/initializers
      - ./configuration:/etc/netbox/config
      - ./reports:/etc/netbox/reports
      - ./scripts:/etc/netbox/scripts
      - ./media:/opt/netbox/netbox/media
    logging: &logging
      options:
        max-size: 5m
        max-file: '3'

  netbox-worker:
    <<: *netbox
    container_name: netbox-worker
    hostname: netbox-worker
    restart: always
    depends_on:
      - redis
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
      - rqworker
    logging:
      <<: *logging

  # postgres
  postgres:
    image: docker.io/postgres:13-alpine
    container_name: netbox-postgres
    hostname: netbox-postgres
    restart: always
    ports:
      - 5444:5432
    env_file: env/postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    logging:
      <<: *logging

  redis:
    image: redis:6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: env/redis.env
    volumes:
      - netbox-redis-data:/data
    logging:
      <<: *logging

  redis-cache:
    image: redis:6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD
    env_file: env/redis-cache.env
    volumes:
      - netbox-redis-cache-data:/data
    logging:
      <<: *logging

volumes:

  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
